// shim for `convert`: generated by mikulibs/build.rs from
// src/lib/libmiku/convert.rs. DO NOT EDIT above the manual marker.
//
// Forwards to the C symbols exported by the library that owns the
// module, resolved at load time by ld-miku. Shims must stay
// stateless: all state lives in the owning library (see README.md).

mod ffi {
    #[allow(unused_imports)] use super::*;
    #[allow(improper_ctypes)]
    extern "C" {
        pub fn miku_strtol(s: *const u8, endptr: *mut *const u8, base: i32) -> i64;
        pub fn miku_strtoul(s: *const u8, endptr: *mut *const u8, base: i32) -> u64;
        pub fn miku_strtod(s: *const u8, endptr: *mut *const u8) -> i64;
        pub fn miku_itoa_base(val: i64, buf: *mut u8, base: i32) -> *mut u8;
        pub fn miku_utoa_base(val: u64, buf: *mut u8, base: i32) -> *mut u8;
    }
}

#[inline]
pub fn miku_strtol(s: *const u8, endptr: *mut *const u8, base: i32) -> i64 { unsafe { ffi::miku_strtol(s, endptr, base) } }
#[inline]
pub fn miku_strtoul(s: *const u8, endptr: *mut *const u8, base: i32) -> u64 { unsafe { ffi::miku_strtoul(s, endptr, base) } }
#[inline]
pub fn miku_strtod(s: *const u8, endptr: *mut *const u8) -> i64 { unsafe { ffi::miku_strtod(s, endptr) } }
#[inline]
pub fn miku_itoa_base(val: i64, buf: *mut u8, base: i32) -> *mut u8 { unsafe { ffi::miku_itoa_base(val, buf, base) } }
#[inline]
pub fn miku_utoa_base(val: u64, buf: *mut u8, base: i32) -> *mut u8 { unsafe { ffi::miku_utoa_base(val, buf, base) } }

// ===== manual additions below (preserved by the generator) =====
