// shim for `ctype`: generated by mikulibs/build.rs from
// src/lib/libmiku/ctype.rs. DO NOT EDIT above the manual marker.
//
// Forwards to the C symbols exported by the library that owns the
// module, resolved at load time by ld-miku. Shims must stay
// stateless: all state lives in the owning library (see README.md).

mod ffi {
    #[allow(unused_imports)] use super::*;
    #[allow(improper_ctypes)]
    extern "C" {
        pub fn miku_isdigit(c: i32) -> i32;
        pub fn miku_isalpha(c: i32) -> i32;
        pub fn miku_isalnum(c: i32) -> i32;
        pub fn miku_isspace(c: i32) -> i32;
        pub fn miku_isupper(c: i32) -> i32;
        pub fn miku_islower(c: i32) -> i32;
        pub fn miku_isprint(c: i32) -> i32;
        pub fn miku_ispunct(c: i32) -> i32;
        pub fn miku_iscntrl(c: i32) -> i32;
        pub fn miku_isxdigit(c: i32) -> i32;
        pub fn miku_toupper(c: i32) -> i32;
        pub fn miku_tolower(c: i32) -> i32;
        pub fn miku_isgraph(c: i32) -> i32;
        pub fn miku_isblank(c: i32) -> i32;
        pub fn miku_isascii(c: i32) -> i32;
        pub fn miku_toascii(c: i32) -> i32;
    }
}

#[inline]
pub fn miku_isdigit(c: i32) -> i32 { unsafe { ffi::miku_isdigit(c) } }
#[inline]
pub fn miku_isalpha(c: i32) -> i32 { unsafe { ffi::miku_isalpha(c) } }
#[inline]
pub fn miku_isalnum(c: i32) -> i32 { unsafe { ffi::miku_isalnum(c) } }
#[inline]
pub fn miku_isspace(c: i32) -> i32 { unsafe { ffi::miku_isspace(c) } }
#[inline]
pub fn miku_isupper(c: i32) -> i32 { unsafe { ffi::miku_isupper(c) } }
#[inline]
pub fn miku_islower(c: i32) -> i32 { unsafe { ffi::miku_islower(c) } }
#[inline]
pub fn miku_isprint(c: i32) -> i32 { unsafe { ffi::miku_isprint(c) } }
#[inline]
pub fn miku_ispunct(c: i32) -> i32 { unsafe { ffi::miku_ispunct(c) } }
#[inline]
pub fn miku_iscntrl(c: i32) -> i32 { unsafe { ffi::miku_iscntrl(c) } }
#[inline]
pub fn miku_isxdigit(c: i32) -> i32 { unsafe { ffi::miku_isxdigit(c) } }
#[inline]
pub fn miku_toupper(c: i32) -> i32 { unsafe { ffi::miku_toupper(c) } }
#[inline]
pub fn miku_tolower(c: i32) -> i32 { unsafe { ffi::miku_tolower(c) } }
#[inline]
pub fn miku_isgraph(c: i32) -> i32 { unsafe { ffi::miku_isgraph(c) } }
#[inline]
pub fn miku_isblank(c: i32) -> i32 { unsafe { ffi::miku_isblank(c) } }
#[inline]
pub fn miku_isascii(c: i32) -> i32 { unsafe { ffi::miku_isascii(c) } }
#[inline]
pub fn miku_toascii(c: i32) -> i32 { unsafe { ffi::miku_toascii(c) } }

// ===== manual additions below (preserved by the generator) =====
