// shim for `env`: generated by mikulibs/build.rs from
// src/lib/libmiku/env.rs. DO NOT EDIT above the manual marker.
//
// Forwards to the C symbols exported by the library that owns the
// module, resolved at load time by ld-miku. Shims must stay
// stateless: all state lives in the owning library (see README.md).

mod ffi {
    #[allow(unused_imports)] use super::*;
    #[allow(improper_ctypes)]
    extern "C" {
        pub fn miku_setenv(key: *const u8, val: *const u8) -> bool;
        pub fn miku_getenv(key: *const u8) -> *const u8;
        pub fn miku_getenv_r(key: *const u8, buf: *mut u8, buf_size: usize) -> i32;
        pub fn miku_unsetenv(key: *const u8) -> bool;
        pub fn miku_hasenv(key: *const u8) -> bool;
        pub fn miku_env_count() -> usize;
        pub fn miku_env_clear() ;
        pub fn miku_env_iter(cb: EnvCallback, ctx: *mut u8) ;
        pub fn miku_putenv(s: *const u8) -> bool;
        pub fn miku_env_init(envp: *const *const u8) -> usize;
    }
}

#[inline]
pub fn miku_setenv(key: *const u8, val: *const u8) -> bool { unsafe { ffi::miku_setenv(key, val) } }
#[inline]
pub fn miku_getenv(key: *const u8) -> *const u8 { unsafe { ffi::miku_getenv(key) } }
#[inline]
pub fn miku_getenv_r(key: *const u8, buf: *mut u8, buf_size: usize) -> i32 { unsafe { ffi::miku_getenv_r(key, buf, buf_size) } }
#[inline]
pub fn miku_unsetenv(key: *const u8) -> bool { unsafe { ffi::miku_unsetenv(key) } }
#[inline]
pub fn miku_hasenv(key: *const u8) -> bool { unsafe { ffi::miku_hasenv(key) } }
#[inline]
pub fn miku_env_count() -> usize { unsafe { ffi::miku_env_count() } }
#[inline]
pub fn miku_env_clear()  { unsafe { ffi::miku_env_clear() } }
#[inline]
pub fn miku_env_iter(cb: EnvCallback, ctx: *mut u8)  { unsafe { ffi::miku_env_iter(cb, ctx) } }
#[inline]
pub fn miku_putenv(s: *const u8) -> bool { unsafe { ffi::miku_putenv(s) } }
#[inline]
pub fn miku_env_init(envp: *const *const u8) -> usize { unsafe { ffi::miku_env_init(envp) } }

// ===== manual additions below (preserved by the generator) =====

pub type EnvCallback = extern "C" fn(*const u8, *const u8, *mut u8);
