// shim for `errno`: generated by mikulibs/build.rs from
// src/lib/libmiku/errno.rs. DO NOT EDIT above the manual marker.
//
// Forwards to the C symbols exported by the library that owns the
// module, resolved at load time by ld-miku. Shims must stay
// stateless: all state lives in the owning library (see README.md).

pub const EOK:      i64 = 0;
pub const EPERM:    i64 = -1;
pub const ENOENT:   i64 = -2;
pub const ESRCH:    i64 = -3;
pub const EINTR:    i64 = -4;
pub const EIO:      i64 = -5;
pub const ENXIO:    i64 = -6;
pub const E2BIG:    i64 = -7;
pub const ENOEXEC:  i64 = -8;
pub const EBADF:    i64 = -9;
pub const ECHILD:   i64 = -10;
pub const EAGAIN:   i64 = -11;
pub const EWOULDBLOCK: i64 = -11;
pub const ENOMEM:   i64 = -12;
pub const EACCES:   i64 = -13;
pub const EFAULT:   i64 = -14;
pub const EBUSY:    i64 = -16;
pub const EEXIST:   i64 = -17;
pub const EXDEV:    i64 = -18;
pub const ENODEV:   i64 = -19;
pub const ENOTDIR:  i64 = -20;
pub const EISDIR:   i64 = -21;
pub const EINVAL:   i64 = -22;
pub const ENFILE:   i64 = -23;
pub const EMFILE:   i64 = -24;
pub const ENOTTY:   i64 = -25;
pub const EFBIG:    i64 = -27;
pub const ENOSPC:   i64 = -28;
pub const ESPIPE:   i64 = -29;
pub const EROFS:    i64 = -30;
pub const EMLINK:   i64 = -31;
pub const EPIPE:    i64 = -32;
pub const EDOM:     i64 = -33;
pub const ERANGE:   i64 = -34;
pub const EDEADLK:  i64 = -35;
pub const ENAMETOOLONG: i64 = -36;
pub const ENOSYS:   i64 = -38;
pub const ENOTEMPTY: i64 = -39;
pub const ELOOP:    i64 = -40;
pub const EOVERFLOW: i64 = -75;
pub const ENOTSOCK: i64 = -88;
pub const EAFNOSUPPORT: i64 = -97;
pub const EADDRINUSE:   i64 = -98;
pub const ENETUNREACH:  i64 = -101;
pub const ECONNRESET:   i64 = -104;
pub const ENOTCONN:     i64 = -107;
pub const ETIMEDOUT:    i64 = -110;
pub const ECONNREFUSED: i64 = -111;

mod ffi {
    #[allow(unused_imports)] use super::*;
    #[allow(improper_ctypes)]
    extern "C" {
        pub fn miku_strerror(code: i64) -> *const u8;
        pub fn miku_errno_name(code: i64) -> *const u8;
        pub fn miku_perror(prefix: *const u8) ;
        pub fn miku_perror_code(prefix: *const u8, code: i64) ;
        pub fn miku_is_error(val: i64) -> bool;
        pub fn miku_to_errno(val: i64) -> i64;
        pub fn miku_set_errno(code: i64) ;
        pub fn miku_get_errno() -> i64;
    }
}

#[inline]
pub fn miku_strerror(code: i64) -> *const u8 { unsafe { ffi::miku_strerror(code) } }
#[inline]
pub fn miku_errno_name(code: i64) -> *const u8 { unsafe { ffi::miku_errno_name(code) } }
#[inline]
pub fn miku_perror(prefix: *const u8)  { unsafe { ffi::miku_perror(prefix) } }
#[inline]
pub fn miku_perror_code(prefix: *const u8, code: i64)  { unsafe { ffi::miku_perror_code(prefix, code) } }
#[inline]
pub fn miku_is_error(val: i64) -> bool { unsafe { ffi::miku_is_error(val) } }
#[inline]
pub fn miku_to_errno(val: i64) -> i64 { unsafe { ffi::miku_to_errno(val) } }
#[inline]
pub fn miku_set_errno(code: i64)  { unsafe { ffi::miku_set_errno(code) } }
#[inline]
pub fn miku_get_errno() -> i64 { unsafe { ffi::miku_get_errno() } }

// ===== manual additions below (preserved by the generator) =====

// Rust-side helpers: errno state lives in core_miku.so, always go through
// the C accessors so every library sees the same errno.

#[inline]
pub fn set_errno(code: i64) { miku_set_errno(code); }

#[inline]
pub fn get_errno() -> i64 { miku_get_errno() }

#[inline]
pub fn is_error(val: i64) -> bool { val < 0 }

#[inline]
pub fn to_errno(val: i64) -> i64 { if val < 0 { -val } else { 0 } }
