// shim for `file`: generated by mikulibs/build.rs from
// src/lib/libmiku/file.rs. DO NOT EDIT above the manual marker.
//
// Forwards to the C symbols exported by the library that owns the
// module, resolved at load time by ld-miku. Shims must stay
// stateless: all state lives in the owning library (see README.md).

pub const O_READ:      u32 = 0x0001;
pub const O_WRITE:     u32 = 0x0002;
pub const O_RDWR:      u32 = 0x0003;
pub const O_APPEND:    u32 = 0x0004;
pub const O_CREATE:    u32 = 0x0008;
pub const O_EXCLUSIVE: u32 = 0x0010;
pub const O_TRUNCATE:  u32 = 0x0020;
pub const O_DIRECTORY: u32 = 0x0040;
pub const SEEK_SET: u64 = 0;
pub const SEEK_CUR: u64 = 1;
pub const SEEK_END: u64 = 2;
pub const KIND_REGULAR:   u8 = 0;
pub const KIND_DIRECTORY: u8 = 1;
pub const KIND_SYMLINK:   u8 = 2;
pub const KIND_CHARDEV:   u8 = 3;
pub const KIND_BLOCKDEV:  u8 = 4;
pub const KIND_PIPE:      u8 = 5;
pub const EMPTY_DIRENT: MikuDirent = MikuDirent {
    name: [0; 64], inode_id: 0, kind: 0, name_len: 0, _reserved: 0,
};

#[repr(C)]
pub struct MikuStat {
    pub size:      u64,
    pub mode:      u32,
    pub nlinks:    u32,
    pub uid:       u16,
    pub gid:       u16,
    pub kind:      u8,
    pub fs_type:   u8,
    pub dev_major: u8,
    pub dev_minor: u8,
    pub atime:     u64,
    pub mtime:     u64,
    pub ctime:     u64,
    pub inode_id:  u64,
    pub blocks:    u32,
    pub _reserved: [u8; 4],
}
#[repr(C)]
pub struct MikuDirent {
    pub name:     [u8; 64],
    pub inode_id: u16,
    pub kind:     u8,
    pub name_len: u8,
    pub _reserved: u32,
}

mod ffi {
    #[allow(unused_imports)] use super::*;
    #[allow(improper_ctypes)]
    extern "C" {
        pub fn miku_open(path: *const u8, path_len: usize, flags: u32, mode: u32) -> i64;
        pub fn miku_open_cstr(path: *const u8) -> i64;
        pub fn miku_open_rw(path: *const u8) -> i64;
        pub fn miku_create(path: *const u8, mode: u32) -> i64;
        pub fn miku_close(fd: i64) -> i64;
        pub fn miku_seek(fd: i64, offset: u64) -> i64;
        pub fn miku_lseek(fd: i64, offset: i64, whence: u64) -> i64;
        pub fn miku_fsize(fd: i64) -> i64;
        pub fn miku_read_fd(fd: i64, buf: *mut u8, len: usize) -> i64;
        pub fn miku_write_fd(fd: i64, buf: *const u8, len: usize) -> i64;
        pub fn miku_read_file(path: *const u8, out_size: *mut usize) -> *mut u8;
        pub fn miku_stat(path: *const u8, st: *mut MikuStat) -> i64;
        pub fn miku_fstat(fd: i64, st: *mut MikuStat) -> i64;
        pub fn miku_mkdir(path: *const u8, mode: u32) -> i64;
        pub fn miku_rmdir(path: *const u8) -> i64;
        pub fn miku_unlink(path: *const u8) -> i64;
        pub fn miku_readdir(path: *const u8, entries: *mut MikuDirent, max_entries: usize) -> i64;
        pub fn miku_rename(old: *const u8, new: *const u8) -> i64;
        pub fn miku_link(old: *const u8, new: *const u8) -> i64;
        pub fn miku_symlink(target: *const u8, linkpath: *const u8) -> i64;
        pub fn miku_readlink(path: *const u8, buf: *mut u8, buf_len: usize) -> i64;
        pub fn miku_chmod(path: *const u8, mode: u32) -> i64;
        pub fn miku_chown(path: *const u8, uid: u32, gid: u32) -> i64;
        pub fn miku_dup(fd: i64) -> i64;
        pub fn miku_dup2(old_fd: i64, new_fd: i64) -> i64;
        pub fn miku_pipe(fds: *mut i64) -> i64;
        pub fn miku_chdir(path: *const u8) -> i64;
        pub fn miku_access(path: *const u8) -> bool;
        pub fn miku_isdir(path: *const u8) -> bool;
        pub fn miku_filesize(path: *const u8) -> i64;
        pub fn miku_ftruncate(fd: i64, length: u64) -> i64;
        pub fn miku_pread(fd: i64, buf: *mut u8, len: usize, offset: i64) -> i64;
        pub fn miku_pwrite(fd: i64, buf: *const u8, len: usize, offset: i64) -> i64;
        pub fn miku_write_file_cstr(path: *const u8, data: *const u8) -> i64;
        pub fn miku_isfile(path: *const u8) -> bool;
        pub fn miku_issymlink(path: *const u8) -> bool;
    }
}

#[inline]
pub fn miku_open(path: *const u8, path_len: usize, flags: u32, mode: u32) -> i64 { unsafe { ffi::miku_open(path, path_len, flags, mode) } }
#[inline]
pub fn miku_open_cstr(path: *const u8) -> i64 { unsafe { ffi::miku_open_cstr(path) } }
#[inline]
pub fn miku_open_rw(path: *const u8) -> i64 { unsafe { ffi::miku_open_rw(path) } }
#[inline]
pub fn miku_create(path: *const u8, mode: u32) -> i64 { unsafe { ffi::miku_create(path, mode) } }
#[inline]
pub fn miku_close(fd: i64) -> i64 { unsafe { ffi::miku_close(fd) } }
#[inline]
pub fn miku_seek(fd: i64, offset: u64) -> i64 { unsafe { ffi::miku_seek(fd, offset) } }
#[inline]
pub fn miku_lseek(fd: i64, offset: i64, whence: u64) -> i64 { unsafe { ffi::miku_lseek(fd, offset, whence) } }
#[inline]
pub fn miku_fsize(fd: i64) -> i64 { unsafe { ffi::miku_fsize(fd) } }
#[inline]
pub fn miku_read_fd(fd: i64, buf: *mut u8, len: usize) -> i64 { unsafe { ffi::miku_read_fd(fd, buf, len) } }
#[inline]
pub fn miku_write_fd(fd: i64, buf: *const u8, len: usize) -> i64 { unsafe { ffi::miku_write_fd(fd, buf, len) } }
#[inline]
pub fn miku_read_file(path: *const u8, out_size: *mut usize) -> *mut u8 { unsafe { ffi::miku_read_file(path, out_size) } }
#[inline]
pub fn miku_stat(path: *const u8, st: *mut MikuStat) -> i64 { unsafe { ffi::miku_stat(path, st) } }
#[inline]
pub fn miku_fstat(fd: i64, st: *mut MikuStat) -> i64 { unsafe { ffi::miku_fstat(fd, st) } }
#[inline]
pub fn miku_mkdir(path: *const u8, mode: u32) -> i64 { unsafe { ffi::miku_mkdir(path, mode) } }
#[inline]
pub fn miku_rmdir(path: *const u8) -> i64 { unsafe { ffi::miku_rmdir(path) } }
#[inline]
pub fn miku_unlink(path: *const u8) -> i64 { unsafe { ffi::miku_unlink(path) } }
#[inline]
pub fn miku_readdir(path: *const u8, entries: *mut MikuDirent, max_entries: usize) -> i64 { unsafe { ffi::miku_readdir(path, entries, max_entries) } }
#[inline]
pub fn miku_rename(old: *const u8, new: *const u8) -> i64 { unsafe { ffi::miku_rename(old, new) } }
#[inline]
pub fn miku_link(old: *const u8, new: *const u8) -> i64 { unsafe { ffi::miku_link(old, new) } }
#[inline]
pub fn miku_symlink(target: *const u8, linkpath: *const u8) -> i64 { unsafe { ffi::miku_symlink(target, linkpath) } }
#[inline]
pub fn miku_readlink(path: *const u8, buf: *mut u8, buf_len: usize) -> i64 { unsafe { ffi::miku_readlink(path, buf, buf_len) } }
#[inline]
pub fn miku_chmod(path: *const u8, mode: u32) -> i64 { unsafe { ffi::miku_chmod(path, mode) } }
#[inline]
pub fn miku_chown(path: *const u8, uid: u32, gid: u32) -> i64 { unsafe { ffi::miku_chown(path, uid, gid) } }
#[inline]
pub fn miku_dup(fd: i64) -> i64 { unsafe { ffi::miku_dup(fd) } }
#[inline]
pub fn miku_dup2(old_fd: i64, new_fd: i64) -> i64 { unsafe { ffi::miku_dup2(old_fd, new_fd) } }
#[inline]
pub fn miku_pipe(fds: *mut i64) -> i64 { unsafe { ffi::miku_pipe(fds) } }
#[inline]
pub fn miku_chdir(path: *const u8) -> i64 { unsafe { ffi::miku_chdir(path) } }
#[inline]
pub fn miku_access(path: *const u8) -> bool { unsafe { ffi::miku_access(path) } }
#[inline]
pub fn miku_isdir(path: *const u8) -> bool { unsafe { ffi::miku_isdir(path) } }
#[inline]
pub fn miku_filesize(path: *const u8) -> i64 { unsafe { ffi::miku_filesize(path) } }
#[inline]
pub fn miku_ftruncate(fd: i64, length: u64) -> i64 { unsafe { ffi::miku_ftruncate(fd, length) } }
#[inline]
pub fn miku_pread(fd: i64, buf: *mut u8, len: usize, offset: i64) -> i64 { unsafe { ffi::miku_pread(fd, buf, len, offset) } }
#[inline]
pub fn miku_pwrite(fd: i64, buf: *const u8, len: usize, offset: i64) -> i64 { unsafe { ffi::miku_pwrite(fd, buf, len, offset) } }
#[inline]
pub fn miku_write_file_cstr(path: *const u8, data: *const u8) -> i64 { unsafe { ffi::miku_write_file_cstr(path, data) } }
#[inline]
pub fn miku_isfile(path: *const u8) -> bool { unsafe { ffi::miku_isfile(path) } }
#[inline]
pub fn miku_issymlink(path: *const u8) -> bool { unsafe { ffi::miku_issymlink(path) } }

// ===== manual additions below (preserved by the generator) =====
