// shim for `heap`: generated by mikulibs/build.rs from
// src/lib/libmiku/heap.rs. DO NOT EDIT above the manual marker.
//
// Forwards to the C symbols exported by the library that owns the
// module, resolved at load time by ld-miku. Shims must stay
// stateless: all state lives in the owning library (see README.md).

mod ffi {
    #[allow(unused_imports)] use super::*;
    #[allow(improper_ctypes)]
    extern "C" {
        pub fn miku_malloc(size: usize) -> *mut u8;
        pub fn miku_free(ptr: *mut u8) ;
        pub fn miku_realloc(ptr: *mut u8, new_size: usize) -> *mut u8;
        pub fn miku_calloc(count: usize, size: usize) -> *mut u8;
        pub fn miku_memalign(align: usize, size: usize) -> *mut u8;
    }
}

#[inline]
pub fn miku_malloc(size: usize) -> *mut u8 { unsafe { ffi::miku_malloc(size) } }
#[inline]
pub fn miku_free(ptr: *mut u8)  { unsafe { ffi::miku_free(ptr) } }
#[inline]
pub fn miku_realloc(ptr: *mut u8, new_size: usize) -> *mut u8 { unsafe { ffi::miku_realloc(ptr, new_size) } }
#[inline]
pub fn miku_calloc(count: usize, size: usize) -> *mut u8 { unsafe { ffi::miku_calloc(count, size) } }
#[inline]
pub fn miku_memalign(align: usize, size: usize) -> *mut u8 { unsafe { ffi::miku_memalign(align, size) } }

// ===== manual additions below (preserved by the generator) =====
