// shim for `io`: generated by mikulibs/build.rs from
// src/lib/libmiku/io.rs. DO NOT EDIT above the manual marker.
//
// Forwards to the C symbols exported by the library that owns the
// module, resolved at load time by ld-miku. Shims must stay
// stateless: all state lives in the owning library (see README.md).

mod ffi {
    #[allow(unused_imports)] use super::*;
    #[allow(improper_ctypes)]
    extern "C" {
        pub fn miku_write(fd: u64, buf: *const u8, len: usize) -> i64;
        pub fn miku_read(fd: u64, buf: *mut u8, len: usize) -> i64;
    }
}

#[inline]
pub fn miku_write(fd: u64, buf: *const u8, len: usize) -> i64 { unsafe { ffi::miku_write(fd, buf, len) } }
#[inline]
pub fn miku_read(fd: u64, buf: *mut u8, len: usize) -> i64 { unsafe { ffi::miku_read(fd, buf, len) } }

// ===== manual additions below (preserved by the generator) =====
