// shim for `math`: generated by mikulibs/build.rs from
// src/lib/libmiku/math.rs. DO NOT EDIT above the manual marker.
//
// Forwards to the C symbols exported by the library that owns the
// module, resolved at load time by ld-miku. Shims must stay
// stateless: all state lives in the owning library (see README.md).

mod ffi {
    #[allow(unused_imports)] use super::*;
    #[allow(improper_ctypes)]
    extern "C" {
        pub fn miku_abs(x: i64) -> i64;
        pub fn miku_min(a: i64, b: i64) -> i64;
        pub fn miku_max(a: i64, b: i64) -> i64;
        pub fn miku_clamp(val: i64, lo: i64, hi: i64) -> i64;
        pub fn miku_swap(a: *mut u64, b: *mut u64) ;
        pub fn miku_umin(a: u64, b: u64) -> u64;
        pub fn miku_umax(a: u64, b: u64) -> u64;
        pub fn miku_gcd(a: u64, b: u64) -> u64;
        pub fn miku_lcm(a: u64, b: u64) -> u64;
        pub fn miku_pow(base: i64, exp: u32) -> i64;
        pub fn miku_upow(base: u64, exp: u32) -> u64;
        pub fn miku_isqrt(n: u64) -> u64;
        pub fn miku_icbrt(n: u64) -> u64;
        pub fn miku_ilog2(n: u64) -> u32;
        pub fn miku_ilog10(n: u64) -> u32;
        pub fn miku_sign(x: i64) -> i32;
        pub fn miku_map(val: i64, in_lo: i64, in_hi: i64, out_lo: i64, out_hi: i64) -> i64;
        pub fn miku_lerp(a: i64, b: i64, t_permille: u32) -> i64;
        pub fn miku_sadd(a: i64, b: i64) -> i64;
        pub fn miku_ssub(a: i64, b: i64) -> i64;
        pub fn miku_smul(a: i64, b: i64) -> i64;
        pub fn miku_usadd(a: u64, b: u64) -> u64;
        pub fn miku_ussub(a: u64, b: u64) -> u64;
        pub fn miku_div_ceil(a: u64, b: u64) -> u64;
        pub fn miku_modpow(base: u64, exp: u64, modulus: u64) -> u64;
        pub fn miku_is_prime(n: u64) -> i32;
        pub fn miku_fib(n: u32) -> u64;
        pub fn miku_factorial(n: u32) -> u64;
        pub fn miku_binomial(n: u64, k: u64) -> u64;
    }
}

#[inline]
pub fn miku_abs(x: i64) -> i64 { unsafe { ffi::miku_abs(x) } }
#[inline]
pub fn miku_min(a: i64, b: i64) -> i64 { unsafe { ffi::miku_min(a, b) } }
#[inline]
pub fn miku_max(a: i64, b: i64) -> i64 { unsafe { ffi::miku_max(a, b) } }
#[inline]
pub fn miku_clamp(val: i64, lo: i64, hi: i64) -> i64 { unsafe { ffi::miku_clamp(val, lo, hi) } }
#[inline]
pub fn miku_swap(a: *mut u64, b: *mut u64)  { unsafe { ffi::miku_swap(a, b) } }
#[inline]
pub fn miku_umin(a: u64, b: u64) -> u64 { unsafe { ffi::miku_umin(a, b) } }
#[inline]
pub fn miku_umax(a: u64, b: u64) -> u64 { unsafe { ffi::miku_umax(a, b) } }
#[inline]
pub fn miku_gcd(a: u64, b: u64) -> u64 { unsafe { ffi::miku_gcd(a, b) } }
#[inline]
pub fn miku_lcm(a: u64, b: u64) -> u64 { unsafe { ffi::miku_lcm(a, b) } }
#[inline]
pub fn miku_pow(base: i64, exp: u32) -> i64 { unsafe { ffi::miku_pow(base, exp) } }
#[inline]
pub fn miku_upow(base: u64, exp: u32) -> u64 { unsafe { ffi::miku_upow(base, exp) } }
#[inline]
pub fn miku_isqrt(n: u64) -> u64 { unsafe { ffi::miku_isqrt(n) } }
#[inline]
pub fn miku_icbrt(n: u64) -> u64 { unsafe { ffi::miku_icbrt(n) } }
#[inline]
pub fn miku_ilog2(n: u64) -> u32 { unsafe { ffi::miku_ilog2(n) } }
#[inline]
pub fn miku_ilog10(n: u64) -> u32 { unsafe { ffi::miku_ilog10(n) } }
#[inline]
pub fn miku_sign(x: i64) -> i32 { unsafe { ffi::miku_sign(x) } }
#[inline]
pub fn miku_map(val: i64, in_lo: i64, in_hi: i64, out_lo: i64, out_hi: i64) -> i64 { unsafe { ffi::miku_map(val, in_lo, in_hi, out_lo, out_hi) } }
#[inline]
pub fn miku_lerp(a: i64, b: i64, t_permille: u32) -> i64 { unsafe { ffi::miku_lerp(a, b, t_permille) } }
#[inline]
pub fn miku_sadd(a: i64, b: i64) -> i64 { unsafe { ffi::miku_sadd(a, b) } }
#[inline]
pub fn miku_ssub(a: i64, b: i64) -> i64 { unsafe { ffi::miku_ssub(a, b) } }
#[inline]
pub fn miku_smul(a: i64, b: i64) -> i64 { unsafe { ffi::miku_smul(a, b) } }
#[inline]
pub fn miku_usadd(a: u64, b: u64) -> u64 { unsafe { ffi::miku_usadd(a, b) } }
#[inline]
pub fn miku_ussub(a: u64, b: u64) -> u64 { unsafe { ffi::miku_ussub(a, b) } }
#[inline]
pub fn miku_div_ceil(a: u64, b: u64) -> u64 { unsafe { ffi::miku_div_ceil(a, b) } }
#[inline]
pub fn miku_modpow(base: u64, exp: u64, modulus: u64) -> u64 { unsafe { ffi::miku_modpow(base, exp, modulus) } }
#[inline]
pub fn miku_is_prime(n: u64) -> i32 { unsafe { ffi::miku_is_prime(n) } }
#[inline]
pub fn miku_fib(n: u32) -> u64 { unsafe { ffi::miku_fib(n) } }
#[inline]
pub fn miku_factorial(n: u32) -> u64 { unsafe { ffi::miku_factorial(n) } }
#[inline]
pub fn miku_binomial(n: u64, k: u64) -> u64 { unsafe { ffi::miku_binomial(n, k) } }

// ===== manual additions below (preserved by the generator) =====
