// shim for `mem`: generated by mikulibs/build.rs from
// src/lib/libmiku/mem.rs. DO NOT EDIT above the manual marker.
//
// Forwards to the C symbols exported by the library that owns the
// module, resolved at load time by ld-miku. Shims must stay
// stateless: all state lives in the owning library (see README.md).

mod ffi {
    #[allow(unused_imports)] use super::*;
    #[allow(improper_ctypes)]
    extern "C" {
        pub fn miku_memset(dst: *mut u8, val: i32, n: usize) -> *mut u8;
        pub fn miku_memcpy(dst: *mut u8, src: *const u8, n: usize) -> *mut u8;
        pub fn miku_memmove(dst: *mut u8, src: *const u8, n: usize) -> *mut u8;
        pub fn miku_memcmp(a: *const u8, b: *const u8, n: usize) -> i32;
        pub fn miku_bzero(dst: *mut u8, n: usize) ;
        pub fn miku_memchr(s: *const u8, c: i32, n: usize) -> *const u8;
        pub fn miku_memrchr(s: *const u8, c: i32, n: usize) -> *const u8;
        pub fn miku_memmem(haystack: *const u8, hlen: usize, needle: *const u8, nlen: usize) -> *const u8;
    }
}

#[inline]
pub fn miku_memset(dst: *mut u8, val: i32, n: usize) -> *mut u8 { unsafe { ffi::miku_memset(dst, val, n) } }
#[inline]
pub fn miku_memcpy(dst: *mut u8, src: *const u8, n: usize) -> *mut u8 { unsafe { ffi::miku_memcpy(dst, src, n) } }
#[inline]
pub fn miku_memmove(dst: *mut u8, src: *const u8, n: usize) -> *mut u8 { unsafe { ffi::miku_memmove(dst, src, n) } }
#[inline]
pub fn miku_memcmp(a: *const u8, b: *const u8, n: usize) -> i32 { unsafe { ffi::miku_memcmp(a, b, n) } }
#[inline]
pub fn miku_bzero(dst: *mut u8, n: usize)  { unsafe { ffi::miku_bzero(dst, n) } }
#[inline]
pub fn miku_memchr(s: *const u8, c: i32, n: usize) -> *const u8 { unsafe { ffi::miku_memchr(s, c, n) } }
#[inline]
pub fn miku_memrchr(s: *const u8, c: i32, n: usize) -> *const u8 { unsafe { ffi::miku_memrchr(s, c, n) } }
#[inline]
pub fn miku_memmem(haystack: *const u8, hlen: usize, needle: *const u8, nlen: usize) -> *const u8 { unsafe { ffi::miku_memmem(haystack, hlen, needle, nlen) } }

// ===== manual additions below (preserved by the generator) =====
