// shim for `num`: generated by mikulibs/build.rs from
// src/lib/libmiku/num.rs. DO NOT EDIT above the manual marker.
//
// Forwards to the C symbols exported by the library that owns the
// module, resolved at load time by ld-miku. Shims must stay
// stateless: all state lives in the owning library (see README.md).

mod ffi {
    #[allow(unused_imports)] use super::*;
    #[allow(improper_ctypes)]
    extern "C" {
        pub fn miku_itoa(val: i64, buf: *mut u8) ;
        pub fn miku_utoa(val: u64, buf: *mut u8) ;
        pub fn miku_atoi(s: *const u8) -> i64;
        pub fn miku_print_int(val: i64) ;
        pub fn miku_print_hex(val: u64) ;
    }
}

#[inline]
pub fn miku_itoa(val: i64, buf: *mut u8)  { unsafe { ffi::miku_itoa(val, buf) } }
#[inline]
pub fn miku_utoa(val: u64, buf: *mut u8)  { unsafe { ffi::miku_utoa(val, buf) } }
#[inline]
pub fn miku_atoi(s: *const u8) -> i64 { unsafe { ffi::miku_atoi(s) } }
#[inline]
pub fn miku_print_int(val: i64)  { unsafe { ffi::miku_print_int(val) } }
#[inline]
pub fn miku_print_hex(val: u64)  { unsafe { ffi::miku_print_hex(val) } }

// ===== manual additions below (preserved by the generator) =====

// plain (non-C-ABI) helpers duplicated from num.rs: pure functions, no state

pub fn utoa_hex(val: u64, buf: *mut u8) -> usize {
    if buf.is_null() { return 0; }
    let mut n = val;
    if n == 0 {
        unsafe { *buf = b'0'; *buf.add(1) = 0; }
        return 1;
    }
    let mut pos = 0usize;
    while n > 0 {
        let d = (n & 0xF) as u8;
        unsafe { *buf.add(pos) = if d < 10 { b'0' + d } else { b'a' + d - 10 }; }
        pos += 1;
        n >>= 4;
    }
    reverse_bytes(buf, 0, pos);
    unsafe { *buf.add(pos) = 0; }
    pos
}

pub fn utoa_hex_upper(val: u64, buf: *mut u8) -> usize {
    if buf.is_null() { return 0; }
    let mut n = val;
    if n == 0 {
        unsafe { *buf = b'0'; *buf.add(1) = 0; }
        return 1;
    }
    let mut pos = 0usize;
    while n > 0 {
        let d = (n & 0xF) as u8;
        unsafe { *buf.add(pos) = if d < 10 { b'0' + d } else { b'A' + d - 10 }; }
        pos += 1;
        n >>= 4;
    }
    reverse_bytes(buf, 0, pos);
    unsafe { *buf.add(pos) = 0; }
    pos
}

pub fn utoa_oct(val: u64, buf: *mut u8) -> usize {
    if buf.is_null() { return 0; }
    let mut n = val;
    if n == 0 {
        unsafe { *buf = b'0'; *buf.add(1) = 0; }
        return 1;
    }
    let mut pos = 0usize;
    while n > 0 {
        unsafe { *buf.add(pos) = b'0' + (n & 7) as u8; }
        pos += 1;
        n >>= 3;
    }
    reverse_bytes(buf, 0, pos);
    unsafe { *buf.add(pos) = 0; }
    pos
}

fn reverse_bytes(buf: *mut u8, start: usize, end: usize) {
    let mut l = start;
    let mut r = end - 1;
    while l < r {
        unsafe {
            let tmp = *buf.add(l);
            *buf.add(l) = *buf.add(r);
            *buf.add(r) = tmp;
        }
        l += 1;
        r -= 1;
    }
}
