// shim for `proc`: generated by mikulibs/build.rs from
// src/lib/libmiku/proc.rs. DO NOT EDIT above the manual marker.
//
// Forwards to the C symbols exported by the library that owns the
// module, resolved at load time by ld-miku. Shims must stay
// stateless: all state lives in the owning library (see README.md).

mod ffi {
    #[allow(unused_imports)] use super::*;
    #[allow(improper_ctypes)]
    extern "C" {
        pub fn miku_exit(code: i64) -> !;
        pub fn miku_getpid() -> u64;
        pub fn miku_getcwd(buf: *mut u8, size: usize) -> *mut u8;
        pub fn miku_brk(addr: u64) -> u64;
        pub fn miku_mmap(addr: u64, len: usize, prot: u64) -> *mut u8;
        pub fn miku_munmap(addr: *mut u8, len: usize) -> i64;
        pub fn miku_mmap_file(addr: u64, len: usize, prot: u64, flags: u64, fd: i64, offset: u64) -> *mut u8;
        pub fn miku_msync(addr: *mut u8, len: usize) -> i64;
        pub fn miku_mprotect(addr: u64, len: usize, prot: u64) -> i64;
        pub fn miku_set_tls(addr: u64) -> i64;
        pub fn miku_get_tls() -> u64;
        pub fn miku_map_lib(name: *const u8, name_len: usize) -> i64;
        pub fn miku_fork() -> i64;
        pub fn miku_waitpid(pid: u64, status: *mut i64) -> i64;
        pub fn miku_kill(pid: u64, sig: u64) -> i64;
        pub fn miku_exec(path: *const u8, argv: *const *const u8, argc: usize) -> i64;
        pub fn miku_execve(path: *const u8, argv: *const *const u8, argc: usize, envp: *const *const u8, envc: usize) -> i64;
    }
}

#[inline]
pub fn miku_exit(code: i64) -> ! { unsafe { ffi::miku_exit(code) } }
#[inline]
pub fn miku_getpid() -> u64 { unsafe { ffi::miku_getpid() } }
#[inline]
pub fn miku_getcwd(buf: *mut u8, size: usize) -> *mut u8 { unsafe { ffi::miku_getcwd(buf, size) } }
#[inline]
pub fn miku_brk(addr: u64) -> u64 { unsafe { ffi::miku_brk(addr) } }
#[inline]
pub fn miku_mmap(addr: u64, len: usize, prot: u64) -> *mut u8 { unsafe { ffi::miku_mmap(addr, len, prot) } }
#[inline]
pub fn miku_munmap(addr: *mut u8, len: usize) -> i64 { unsafe { ffi::miku_munmap(addr, len) } }
#[inline]
pub fn miku_mmap_file(addr: u64, len: usize, prot: u64, flags: u64, fd: i64, offset: u64) -> *mut u8 { unsafe { ffi::miku_mmap_file(addr, len, prot, flags, fd, offset) } }
#[inline]
pub fn miku_msync(addr: *mut u8, len: usize) -> i64 { unsafe { ffi::miku_msync(addr, len) } }
#[inline]
pub fn miku_mprotect(addr: u64, len: usize, prot: u64) -> i64 { unsafe { ffi::miku_mprotect(addr, len, prot) } }
#[inline]
pub fn miku_set_tls(addr: u64) -> i64 { unsafe { ffi::miku_set_tls(addr) } }
#[inline]
pub fn miku_get_tls() -> u64 { unsafe { ffi::miku_get_tls() } }
#[inline]
pub fn miku_map_lib(name: *const u8, name_len: usize) -> i64 { unsafe { ffi::miku_map_lib(name, name_len) } }
#[inline]
pub fn miku_fork() -> i64 { unsafe { ffi::miku_fork() } }
#[inline]
pub fn miku_waitpid(pid: u64, status: *mut i64) -> i64 { unsafe { ffi::miku_waitpid(pid, status) } }
#[inline]
pub fn miku_kill(pid: u64, sig: u64) -> i64 { unsafe { ffi::miku_kill(pid, sig) } }
#[inline]
pub fn miku_exec(path: *const u8, argv: *const *const u8, argc: usize) -> i64 { unsafe { ffi::miku_exec(path, argv, argc) } }
#[inline]
pub fn miku_execve(path: *const u8, argv: *const *const u8, argc: usize, envp: *const *const u8, envc: usize) -> i64 { unsafe { ffi::miku_execve(path, argv, argc, envp, envc) } }

// ===== manual additions below (preserved by the generator) =====
