// shim for `random`: generated by mikulibs/build.rs from
// src/lib/libmiku/random.rs. DO NOT EDIT above the manual marker.
//
// Forwards to the C symbols exported by the library that owns the
// module, resolved at load time by ld-miku. Shims must stay
// stateless: all state lives in the owning library (see README.md).

mod ffi {
    #[allow(unused_imports)] use super::*;
    #[allow(improper_ctypes)]
    extern "C" {
        pub fn miku_srand(seed: u64) ;
        pub fn miku_rand() -> u64;
        pub fn miku_rand_range(lo: u64, hi: u64) -> u64;
        pub fn miku_rand_u32() -> u32;
        pub fn miku_rand_bytes(buf: *mut u8, len: usize) ;
        pub fn miku_rand_bool() -> bool;
        pub fn miku_rand_uniform(bound: u64) -> u64;
        pub fn miku_rand_i64(lo: i64, hi: i64) -> i64;
        pub fn miku_rand_frac_million() -> u64;
        pub fn miku_rand_dice(sides: u32) -> u32;
        pub fn miku_rand_sample(n: usize, k: usize, out: *mut usize) -> usize;
        pub fn miku_rand_weighted(weights: *const u64, n: usize) -> usize;
        pub fn miku_rand_perm(n: usize, out: *mut usize) ;
        pub fn miku_rand_shuffle(data: *mut u8, count: usize, elem_size: usize) ;
    }
}

#[inline]
pub fn miku_srand(seed: u64)  { unsafe { ffi::miku_srand(seed) } }
#[inline]
pub fn miku_rand() -> u64 { unsafe { ffi::miku_rand() } }
#[inline]
pub fn miku_rand_range(lo: u64, hi: u64) -> u64 { unsafe { ffi::miku_rand_range(lo, hi) } }
#[inline]
pub fn miku_rand_u32() -> u32 { unsafe { ffi::miku_rand_u32() } }
#[inline]
pub fn miku_rand_bytes(buf: *mut u8, len: usize)  { unsafe { ffi::miku_rand_bytes(buf, len) } }
#[inline]
pub fn miku_rand_bool() -> bool { unsafe { ffi::miku_rand_bool() } }
#[inline]
pub fn miku_rand_uniform(bound: u64) -> u64 { unsafe { ffi::miku_rand_uniform(bound) } }
#[inline]
pub fn miku_rand_i64(lo: i64, hi: i64) -> i64 { unsafe { ffi::miku_rand_i64(lo, hi) } }
#[inline]
pub fn miku_rand_frac_million() -> u64 { unsafe { ffi::miku_rand_frac_million() } }
#[inline]
pub fn miku_rand_dice(sides: u32) -> u32 { unsafe { ffi::miku_rand_dice(sides) } }
#[inline]
pub fn miku_rand_sample(n: usize, k: usize, out: *mut usize) -> usize { unsafe { ffi::miku_rand_sample(n, k, out) } }
#[inline]
pub fn miku_rand_weighted(weights: *const u64, n: usize) -> usize { unsafe { ffi::miku_rand_weighted(weights, n) } }
#[inline]
pub fn miku_rand_perm(n: usize, out: *mut usize)  { unsafe { ffi::miku_rand_perm(n, out) } }
#[inline]
pub fn miku_rand_shuffle(data: *mut u8, count: usize, elem_size: usize)  { unsafe { ffi::miku_rand_shuffle(data, count, elem_size) } }

// ===== manual additions below (preserved by the generator) =====
