// shim for `signal`: generated by mikulibs/build.rs from
// src/lib/libmiku/signal.rs. DO NOT EDIT above the manual marker.
//
// Forwards to the C symbols exported by the library that owns the
// module, resolved at load time by ld-miku. Shims must stay
// stateless: all state lives in the owning library (see README.md).

pub const SIG_HUP: u32 = 1;
pub const SIG_INT: u32 = 2;
pub const SIG_QUIT: u32 = 3;
pub const SIG_ILL: u32 = 4;
pub const SIG_TRAP: u32 = 5;
pub const SIG_ABRT: u32 = 6;
pub const SIG_FPE: u32 = 8;
pub const SIG_KILL: u32 = 9;
pub const SIG_SEGV: u32 = 11;
pub const SIG_PIPE: u32 = 13;
pub const SIG_ALRM: u32 = 14;
pub const SIG_TERM: u32 = 15;
pub const SIG_CHLD: u32 = 17;
pub const SIG_CONT: u32 = 18;
pub const SIG_STOP: u32 = 19;
pub const SIG_USR1: u32 = 10;
pub const SIG_USR2: u32 = 12;
pub const SA_RESETHAND: u32 = 1; // reset handler after one delivery
pub const SA_NODEFER:   u32 = 2; // don't block signal during handler
pub const SA_RESTART:   u32 = 4; // restart interrupted syscalls

#[repr(C)]
#[derive(Copy, Clone)]
pub struct MikuSigaction {
    pub handler: Option<SignalHandler>,
    pub flags: u32,
    pub mask: u32, // signals to block during handler execution
}

const EMPTY_SIGACTION: MikuSigaction = MikuSigaction {
    handler: None, flags: 0, mask: 0,
};

mod ffi {
    #[allow(unused_imports)] use super::*;
    #[allow(improper_ctypes)]
    extern "C" {
        pub fn __miku_sig_dispatch_any(sig: u32) -> bool;
        pub fn miku_signal_init() ;
        pub fn miku_signal(sig: u32, handler: Option<SignalHandler>) -> Option<SignalHandler>;
        pub fn miku_signal_dispatch(sig: u32) -> bool;
        pub fn miku_signal_has_handler(sig: u32) -> bool;
        pub fn miku_signal_reset_all() ;
        pub fn miku_signal_block(sig: u32) ;
        pub fn miku_signal_unblock(sig: u32) ;
        pub fn miku_signal_is_blocked(sig: u32) -> bool;
        pub fn miku_signal_get_mask() -> u32;
        pub fn miku_signal_set_mask(mask: u32) -> u32;
        pub fn miku_sigaction(sig: u32, act: *const MikuSigaction, oldact: *mut MikuSigaction) -> i32;
        pub fn miku_sigaction_dispatch(sig: u32) -> bool;
        pub fn miku_signal_raise(sig: u32) -> i32;
        pub fn miku_signal_pending() -> u32;
    }
}

#[inline]
pub fn __miku_sig_dispatch_any(sig: u32) -> bool { unsafe { ffi::__miku_sig_dispatch_any(sig) } }
#[inline]
pub fn miku_signal_init()  { unsafe { ffi::miku_signal_init() } }
#[inline]
pub fn miku_signal(sig: u32, handler: Option<SignalHandler>) -> Option<SignalHandler> { unsafe { ffi::miku_signal(sig, handler) } }
#[inline]
pub fn miku_signal_dispatch(sig: u32) -> bool { unsafe { ffi::miku_signal_dispatch(sig) } }
#[inline]
pub fn miku_signal_has_handler(sig: u32) -> bool { unsafe { ffi::miku_signal_has_handler(sig) } }
#[inline]
pub fn miku_signal_reset_all()  { unsafe { ffi::miku_signal_reset_all() } }
#[inline]
pub fn miku_signal_block(sig: u32)  { unsafe { ffi::miku_signal_block(sig) } }
#[inline]
pub fn miku_signal_unblock(sig: u32)  { unsafe { ffi::miku_signal_unblock(sig) } }
#[inline]
pub fn miku_signal_is_blocked(sig: u32) -> bool { unsafe { ffi::miku_signal_is_blocked(sig) } }
#[inline]
pub fn miku_signal_get_mask() -> u32 { unsafe { ffi::miku_signal_get_mask() } }
#[inline]
pub fn miku_signal_set_mask(mask: u32) -> u32 { unsafe { ffi::miku_signal_set_mask(mask) } }
#[inline]
pub fn miku_sigaction(sig: u32, act: *const MikuSigaction, oldact: *mut MikuSigaction) -> i32 { unsafe { ffi::miku_sigaction(sig, act, oldact) } }
#[inline]
pub fn miku_sigaction_dispatch(sig: u32) -> bool { unsafe { ffi::miku_sigaction_dispatch(sig) } }
#[inline]
pub fn miku_signal_raise(sig: u32) -> i32 { unsafe { ffi::miku_signal_raise(sig) } }
#[inline]
pub fn miku_signal_pending() -> u32 { unsafe { ffi::miku_signal_pending() } }

// ===== manual additions below (preserved by the generator) =====

pub type SignalHandler = extern "C" fn(u32);
