// shim for `string`: generated by mikulibs/build.rs from
// src/lib/libmiku/string.rs. DO NOT EDIT above the manual marker.
//
// Forwards to the C symbols exported by the library that owns the
// module, resolved at load time by ld-miku. Shims must stay
// stateless: all state lives in the owning library (see README.md).

mod ffi {
    #[allow(unused_imports)] use super::*;
    #[allow(improper_ctypes)]
    extern "C" {
        pub fn miku_strlen(s: *const u8) -> usize;
        pub fn miku_strcmp(a: *const u8, b: *const u8) -> i32;
        pub fn miku_strncmp(a: *const u8, b: *const u8, n: usize) -> i32;
        pub fn miku_strcpy(dst: *mut u8, src: *const u8) -> *mut u8;
        pub fn miku_strncpy(dst: *mut u8, src: *const u8, n: usize) -> *mut u8;
        pub fn miku_strcat(dst: *mut u8, src: *const u8) -> *mut u8;
        pub fn miku_strncat(dst: *mut u8, src: *const u8, n: usize) -> *mut u8;
        pub fn miku_strchr(s: *const u8, c: i32) -> *const u8;
        pub fn miku_strrchr(s: *const u8, c: i32) -> *const u8;
        pub fn miku_strstr(haystack: *const u8, needle: *const u8) -> *const u8;
        pub fn miku_strdup(s: *const u8) -> *mut u8;
        pub fn miku_strndup(s: *const u8, n: usize) -> *mut u8;
        pub fn miku_strlcpy(dst: *mut u8, src: *const u8, size: usize) -> usize;
        pub fn miku_strlcat(dst: *mut u8, src: *const u8, size: usize) -> usize;
        pub fn miku_strtok(s: *mut u8, delim: *const u8) -> *mut u8;
        pub fn miku_strtok_r(s: *mut u8, delim: *const u8, saveptr: *mut *mut u8) -> *mut u8;
        pub fn miku_strnlen(s: *const u8, maxlen: usize) -> usize;
        pub fn miku_strcasecmp(a: *const u8, b: *const u8) -> i32;
        pub fn miku_strncasecmp(a: *const u8, b: *const u8, n: usize) -> i32;
        pub fn miku_strsep(stringp: *mut *mut u8, delim: *const u8) -> *mut u8;
        pub fn miku_strpbrk(s: *const u8, accept: *const u8) -> *const u8;
        pub fn miku_strspn(s: *const u8, accept: *const u8) -> usize;
        pub fn miku_strcspn(s: *const u8, reject: *const u8) -> usize;
    }
}

#[inline]
pub fn miku_strlen(s: *const u8) -> usize { unsafe { ffi::miku_strlen(s) } }
#[inline]
pub fn miku_strcmp(a: *const u8, b: *const u8) -> i32 { unsafe { ffi::miku_strcmp(a, b) } }
#[inline]
pub fn miku_strncmp(a: *const u8, b: *const u8, n: usize) -> i32 { unsafe { ffi::miku_strncmp(a, b, n) } }
#[inline]
pub fn miku_strcpy(dst: *mut u8, src: *const u8) -> *mut u8 { unsafe { ffi::miku_strcpy(dst, src) } }
#[inline]
pub fn miku_strncpy(dst: *mut u8, src: *const u8, n: usize) -> *mut u8 { unsafe { ffi::miku_strncpy(dst, src, n) } }
#[inline]
pub fn miku_strcat(dst: *mut u8, src: *const u8) -> *mut u8 { unsafe { ffi::miku_strcat(dst, src) } }
#[inline]
pub fn miku_strncat(dst: *mut u8, src: *const u8, n: usize) -> *mut u8 { unsafe { ffi::miku_strncat(dst, src, n) } }
#[inline]
pub fn miku_strchr(s: *const u8, c: i32) -> *const u8 { unsafe { ffi::miku_strchr(s, c) } }
#[inline]
pub fn miku_strrchr(s: *const u8, c: i32) -> *const u8 { unsafe { ffi::miku_strrchr(s, c) } }
#[inline]
pub fn miku_strstr(haystack: *const u8, needle: *const u8) -> *const u8 { unsafe { ffi::miku_strstr(haystack, needle) } }
#[inline]
pub fn miku_strdup(s: *const u8) -> *mut u8 { unsafe { ffi::miku_strdup(s) } }
#[inline]
pub fn miku_strndup(s: *const u8, n: usize) -> *mut u8 { unsafe { ffi::miku_strndup(s, n) } }
#[inline]
pub fn miku_strlcpy(dst: *mut u8, src: *const u8, size: usize) -> usize { unsafe { ffi::miku_strlcpy(dst, src, size) } }
#[inline]
pub fn miku_strlcat(dst: *mut u8, src: *const u8, size: usize) -> usize { unsafe { ffi::miku_strlcat(dst, src, size) } }
#[inline]
pub fn miku_strtok(s: *mut u8, delim: *const u8) -> *mut u8 { unsafe { ffi::miku_strtok(s, delim) } }
#[inline]
pub fn miku_strtok_r(s: *mut u8, delim: *const u8, saveptr: *mut *mut u8) -> *mut u8 { unsafe { ffi::miku_strtok_r(s, delim, saveptr) } }
#[inline]
pub fn miku_strnlen(s: *const u8, maxlen: usize) -> usize { unsafe { ffi::miku_strnlen(s, maxlen) } }
#[inline]
pub fn miku_strcasecmp(a: *const u8, b: *const u8) -> i32 { unsafe { ffi::miku_strcasecmp(a, b) } }
#[inline]
pub fn miku_strncasecmp(a: *const u8, b: *const u8, n: usize) -> i32 { unsafe { ffi::miku_strncasecmp(a, b, n) } }
#[inline]
pub fn miku_strsep(stringp: *mut *mut u8, delim: *const u8) -> *mut u8 { unsafe { ffi::miku_strsep(stringp, delim) } }
#[inline]
pub fn miku_strpbrk(s: *const u8, accept: *const u8) -> *const u8 { unsafe { ffi::miku_strpbrk(s, accept) } }
#[inline]
pub fn miku_strspn(s: *const u8, accept: *const u8) -> usize { unsafe { ffi::miku_strspn(s, accept) } }
#[inline]
pub fn miku_strcspn(s: *const u8, reject: *const u8) -> usize { unsafe { ffi::miku_strcspn(s, reject) } }

// ===== manual additions below (preserved by the generator) =====
