// shim for `time`: generated by mikulibs/build.rs from
// src/lib/libmiku/time.rs. DO NOT EDIT above the manual marker.
//
// Forwards to the C symbols exported by the library that owns the
// module, resolved at load time by ld-miku. Shims must stay
// stateless: all state lives in the owning library (see README.md).

mod ffi {
    #[allow(unused_imports)] use super::*;
    #[allow(improper_ctypes)]
    extern "C" {
        pub fn miku_sleep(ticks: u64) ;
        pub fn miku_sleep_ms(ms: u64) ;
        pub fn miku_uptime() -> u64;
        pub fn miku_uptime_ms() -> u64;
        pub fn miku_yield() ;
    }
}

#[inline]
pub fn miku_sleep(ticks: u64)  { unsafe { ffi::miku_sleep(ticks) } }
#[inline]
pub fn miku_sleep_ms(ms: u64)  { unsafe { ffi::miku_sleep_ms(ms) } }
#[inline]
pub fn miku_uptime() -> u64 { unsafe { ffi::miku_uptime() } }
#[inline]
pub fn miku_uptime_ms() -> u64 { unsafe { ffi::miku_uptime_ms() } }
#[inline]
pub fn miku_yield()  { unsafe { ffi::miku_yield() } }

// ===== manual additions below (preserved by the generator) =====
