// shim for `utf8`: generated by mikulibs/build.rs from
// src/lib/libmiku/utf8.rs. DO NOT EDIT above the manual marker.
//
// Forwards to the C symbols exported by the library that owns the
// module, resolved at load time by ld-miku. Shims must stay
// stateless: all state lives in the owning library (see README.md).

mod ffi {
    #[allow(unused_imports)] use super::*;
    #[allow(improper_ctypes)]
    extern "C" {
        pub fn miku_utf8_encode(codepoint: u32, out: *mut u8) -> usize;
        pub fn miku_utf8_decode(data: *const u8, len: usize, bytes_consumed: *mut usize) -> u32;
        pub fn miku_utf8_len(s: *const u8, byte_len: usize) -> usize;
        pub fn miku_utf8_strlen(s: *const u8) -> usize;
        pub fn miku_utf8_valid(s: *const u8, len: usize) -> bool;
        pub fn miku_utf8_offset(s: *const u8, byte_len: usize, n: usize) -> usize;
        pub fn miku_utf8_is_boundary(s: *const u8, len: usize, pos: usize) -> bool;
    }
}

#[inline]
pub fn miku_utf8_encode(codepoint: u32, out: *mut u8) -> usize { unsafe { ffi::miku_utf8_encode(codepoint, out) } }
#[inline]
pub fn miku_utf8_decode(data: *const u8, len: usize, bytes_consumed: *mut usize) -> u32 { unsafe { ffi::miku_utf8_decode(data, len, bytes_consumed) } }
#[inline]
pub fn miku_utf8_len(s: *const u8, byte_len: usize) -> usize { unsafe { ffi::miku_utf8_len(s, byte_len) } }
#[inline]
pub fn miku_utf8_strlen(s: *const u8) -> usize { unsafe { ffi::miku_utf8_strlen(s) } }
#[inline]
pub fn miku_utf8_valid(s: *const u8, len: usize) -> bool { unsafe { ffi::miku_utf8_valid(s, len) } }
#[inline]
pub fn miku_utf8_offset(s: *const u8, byte_len: usize, n: usize) -> usize { unsafe { ffi::miku_utf8_offset(s, byte_len, n) } }
#[inline]
pub fn miku_utf8_is_boundary(s: *const u8, len: usize, pos: usize) -> bool { unsafe { ffi::miku_utf8_is_boundary(s, len, pos) } }

// ===== manual additions below (preserved by the generator) =====
