[package]
name    = "miku-apps"
version = "0.0.1"
edition = "2021"

[workspace]

[profile.release]
opt-level = 1
lto = false

[[bin]]
name = "test_full"
path = "src/test_full.rs"

[[bin]]
name = "hello"
path = "src/hello.rs"

[[bin]]
name = "mmaptest"
path = "src/mmaptest.rs"

[[bin]]
name = "envtest"
path = "src/envtest.rs"

[[bin]]
name = "sigtest"
path = "src/sigtest.rs"

[[bin]]
name = "spin"
path = "src/spin.rs"

[[bin]]
name = "msh"
path = "src/msh.rs"
