pub static LDSO_BYTES: &[u8] =
    include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/lib/ld_miku/ld-miku.bin"));

/// The split miku system libraries (built from mikulibs/, sources in
/// src/lib/mikulibs/). Preloaded into the solib cache and installed
/// into /lib by the VFS bootstrap.
pub struct MikuLib {
    pub name: &'static str,
    pub bytes: &'static [u8],
}

// The table itself is generated by the root build.rs from
// src/lib/mikulibs/libs.list (the shared library manifest), so the preload
// set stays in sync with what the builder produces.
include!(concat!(env!("OUT_DIR"), "/miku_libs.rs"));
